export const projectInformation = [
    // Example of the Basic Format Needed : 
    // {
    //     img: "Image address that you would like to use",
    //     title: "Project Title",
    //     languages: ["Lanuage1, Lanuage2, Language3"],
    //     type : "Web Development",
    //     link: "https://github.com/Victoria-Williamson",
    //     author: "Me",
    //     description: "Description",
    // },
    {
        img: "https://images.unsplash.com/photo-1535982330050-f1c2fb79ff78?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1934&q=80",
        title: "AllKnightStudy",
        languages: ["JavaScript", "CSS", "HTML", "React"],
        type : "Web Development",
        link: "https://github.com/Victoria-Williamson/ShellHacks2020-allKnightStudy",
        github: "https://github.com/Victoria-Williamson/ShellHacks2020-allKnightStudy",
        timeline: "September 2020",
        description: "Worked on the frontend by importing and making fuctional design components and used firebase to create a database for the users",
        ft: 0,
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bWFwfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        title: "GeoSkill",
        languages: ["JavaScript", "CSS", "HTML", "React"],
        type : "Web Development",
        link: "https://www.youtube.com/watch?v=W5V7KygMbTk",
        github: "https://github.com/Victoria-Williamson/geoSkill",
        timeline: "October 2020",
        description: "Created react components to handle API calls, designed the application, and created the front end",
        ft:true,
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Suggestify",
        languages: ["JavaScript", "CSS", "HTML", "React"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "November 2020",
        description: "Created react components to handle API calls, designed the application, and created the front end",
    },
   

]

export const allProjects =
[
    {
        img: "https://images.unsplash.com/photo-1535982330050-f1c2fb79ff78?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1934&q=80",
        title: "All Knight Study",
        languages: ["JavaScript", "CSS", "HTML", "React"],
        type : "Web Development",
        link: "https://github.com/Victoria-Williamson/ShellHacks2020-allKnightStudy",
        github: "https://github.com/Victoria-Williamson/ShellHacks2020-allKnightStudy",
        timeline: "September 2020",
        inspo:"https://github.com/Victoria-Williamson/ShellHacks2020-allKnightStudy",
        description: "Worked on the frontend by importing and making fuctional design components and used firebase to create a database for the users",
        summary:" The goal of this application is to create a new web application that can give users a temporary study buddy to safely make new friends over quarantine. This applicaiton is not fully funcitoning yet, but will hopefully be done soon. Currently we are working on creating a sign in process and way of connecting study buddies with each other through their accounts. Once an account is created the studybuddies will be able to connet with other people and via. video chat and chat box.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bWFwfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        title: "GeoSkill",
        languages: ["JavaScript", "CSS", "HTML", "React"],
        type : "Web Development",
        link: "https://www.youtube.com/watch?v=W5V7KygMbTk",
        github: "https://github.com/Victoria-Williamson/geoSkill",
        timeline: "October 2020",
        description: "Created react components to handle API calls, designed the application, and created the front end",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
        title: "Suggestify",
        languages: ["JavaScript", "CSS", "HTML", "React", "React Bootstrap", "API", "Firebase"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "November 2020",
        description: "Created react components to handle API calls, designed the application, and created the front end",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1500333070776-343c73e1eb4a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80",
        title: "Web Application",
        languages: ["JavaScript", "CSS", "HTML", "React", "React Bootstrap"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1619468129361-605ebea04b44?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80",
        title: "Mobile Application",
        languages: ["JavaScript", "React Native", "Figma"],
        type : "Other",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
        title: "Algorithms for Machine Learning Project 1 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1569396116180-210c182bedb8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1049&q=80",
        title: "Algorithms for Machine Learning Project 2 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1518932945647-7a1c969f8be2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80",
        title: "Algorithms for Machine Learning Project 3 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80",
        title: "Algorithms for Machine Learning Project 4 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1616012480717-fd9867059ca0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=925&q=80",
        title: "CNN X-Ray",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1470790376778-a9fbc86d70e2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=649&q=80",
        title: "Portfolio Site",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "May 2021 - Current",
        description: "The site you are looking at right now!",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c3RhdGlzdGljc3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        title: "Classification ML Project",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "Summer 2021",
        description: "The site you are looking at right now!",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Regression ML Project",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "Summer 2021",
        description: "The site you are looking at right now!",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "CV ML Project",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "Summer 2021",
        description: "The site you are looking at right now!",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "NN ML Project",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Machine Learning",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "Summer 2021",
        description: "The site you are looking at right now!",
        summary:" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dolor velit, mollis at purus non, pulvinar gravida nisl. Etiam diam enim, vestibulum eget rhoncus non, vehicula nec nisl. Mauris vel eleifend enim. Suspendisse potenti. Vestibulum ultrices orci id augue pellentesque, at sollicitudin lorem tempor. Ut malesuada elit vehicula, molestie nisl a, consectetur metus. Donec ultricies finibus magna sed venenatis. Sed cursus risus eget turpis tristique, ut tempus elit sagittis. Curabitur lacus tellus, maximus ut elit ut, rutrum porttitor leo. Donec consequat fermentum aliquam.",
        learned:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra ante in leo molestie sagittis. Cras a vestibulum nibh. Sed quis ante vitae metus vulputate fermentum. Praesent venenatis vel tortor vitae commodo. Aliquam varius, dui sit amet fringilla sollicitudin, erat ligula tempor diam, eu finibus erat diam dapibus nisi. Aliquam eu nunc sodales, interdum nibh sit amet, ornare nunc. Praesent lacus enim, vehicula bibendum accumsan eget, hendrerit at mauris. "
    },
]