const projectInformation = [
    // Example of the Basic Format Needed : 
    // {
    //     img: "Image address that you would like to use",
    //     title: "Project Title",
    //     languages: ["Lanuage1, Lanuage2, Language3"],
    //     type : "Web Development",
    //     link: "https://github.com/Victoria-Williamson",
    //     author: "Me",
    //     description: "Description",
    // },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "AllKnightStudy",
        languages: ["JavaScript", "CSS", "HTML", "React"],
        type : "Web Development",
        link: "https://github.com/Victoria-Williamson/ShellHacks2020-allKnightStudy",
        github: "https://github.com/Victoria-Williamson/ShellHacks2020-allKnightStudy",
        timeline: "September 2020",
        description: "Worked on the frontend by importing and making fuctional design components and used firebase to create a database for the users",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "GeoSkill",
        languages: ["JavaScript", "CSS", "HTML", "React"],
        type : "Web Development",
        link: "https://www.youtube.com/watch?v=W5V7KygMbTk",
        github: "https://github.com/Victoria-Williamson/geoSkill",
        timeline: "October 2020",
        description: "Created react components to handle API calls, designed the application, and created the front end",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Suggestify",
        languages: ["JavaScript", "CSS", "HTML", "React", "React Bootstrap", "API", "Firebase"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "November 2020",
        description: "Created react components to handle API calls, designed the application, and created the front end",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Web Application",
        languages: ["JavaScript", "CSS", "HTML", "React", "React Bootstrap"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Mobile Application",
        languages: ["JavaScript", "React Native", "Figma"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Algorithms for Machine Learning Project 1 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Algorithms for Machine Learning Project 2 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Algorithms for Machine Learning Project 3 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Algorithms for Machine Learning Project 4 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Algorithms for Machine Learning Project 5 ",
        languages: ["Python","Pandas", "Numpy","sklearn"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "March 2020 - November 2020",
        description: "Application Worked on with Undergraduate Research",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Portfolio Site",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "May 2021 - Current",
        description: "The site you are looking at right now!",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Classification Machine Learning Project",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "Summer 2021",
        description: "The site you are looking at right now!",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Regression Machine Learning Project",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "Summer 2021",
        description: "The site you are looking at right now!",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Computer Vision Machine Learning Project",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "Summer 2021",
        description: "The site you are looking at right now!",
    },
    {
        img: "https://lh3.googleusercontent.com/pw/ACtC-3ej1Hq6IOxshfBV8Fr4Pk2ybc7vpgnjbWvLDFpLaVp_P-VDMBVwSxqKgqeFBvTXRVGxQbzkETRqaCwf5buWHEh87B-bOMpqMNrq_VYEJnq9jxi2MF9o9d0Rd0Z4n4A75GKkLErD33qAqm2x76j-NkAnvw=w1269-h912-no?authuser=0",
        title: "Neural Network Machine Learning Project",
        languages: ["React", "Figma", "Material UI", "React Bootstrap", "Firebase"],
        type : "Web Development",
        link: "https://devpost.com/software/suggestify-j2cplv",
        github: "https://github.com/Victoria-Williamson/Suggestify",
        timeline: "Summer 2021",
        description: "The site you are looking at right now!",
    },

]
export default projectInformation;